### ISSUE TITLE
Unable to communicate with key server

### ISSUE THREAD

**Issue by EmmEff** [sylabs/scs-key-client#32]
API calls do not work if key server base URL contains path element(s) (ie. https://server.com/keys)

**Comment by tri-adam** [comment]
@EmmEff, unfortunately I think we'll have to complicate the URL routing here. The path component of endpoints defined by the [OpenPGP HTTP Keyserver Protocol (HKP)](https://tools.ietf.org/html/draft-shaw-openpgp-hkp-00) _require_ the absolute path to start with `/pks`. More detail in https://github.com/sylabs/scs-key-client/issues/28#issuecomment-615881928.

**Comment by EmmEff** [comment]
We need to follow the OpenPGP spec by using `/pks` endpoint. Closing
